{% set name = "archinfo" %}
{% set version = "9.2.174" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/archinfo-{{ version }}.tar.gz
  sha256: 79bf46bc4866b72fab42c05c42ecdd2216dd8f0647a0a1c4ff596e0babb71f69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8

test:
  imports:
    - archinfo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/angr/archinfo
  summary: Classes with architecture-specific information useful to other projects.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YannickEttwein
