{% set name = "archinfo" %}
{% set version = "9.2.103" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/archinfo-{{ version }}.tar.gz
  sha256: c55f90fc2439cfd82f4316b06cda807ba4bb970dd87a04b48ebd2d071e17f24c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8

test:
  imports:
    - archinfo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/angr/archinfo
  summary: Classes with architecture-specific information useful to other projects.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YannickEttwein
