{% set name = "archinfo" %}
{% set version = "9.2.135" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/archinfo-{{ version }}.tar.gz
  sha256: bade6cc34abc7107ea628e42d2d98002993da82b4d07b1d7e310343fe463a50a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - archinfo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/angr/archinfo
  summary: Classes with architecture-specific information useful to other projects.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YannickEttwein
