{% set name = "archinfo" %}
{% set version = "9.2.149" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/archinfo-{{ version }}.tar.gz
  sha256: 3d6e11d4beecf23755255bf1f9395aed8a7afd7afb6a6f901d8e763f998f9ac7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8

test:
  imports:
    - archinfo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/angr/archinfo
  summary: Classes with architecture-specific information useful to other projects.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YannickEttwein
