{% set name = "archinfo" %}
{% set version = "9.2.134" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/archinfo-{{ version }}.tar.gz
  sha256: 4d6d9f872e6db5e83c577998a7ea2a0d900039b0ceab7774ec2b15e6bcd7d669

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8

test:
  imports:
    - archinfo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/angr/archinfo
  summary: Classes with architecture-specific information useful to other projects.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YannickEttwein
